### ISSUE TITLE
Multiple Inputs 

### ISSUE THREAD

**Issue by aamirrr-m** [DessimozLab/fold_tree#13]
Hello, 

I was wondering if I could use multiple inputs to generate the structural tree? If I had structures for some proteins but they do not have Uniprot IDs and combined this with a list of Uniprot IDs that I do have, is it currently possible to generate a structural tree this way?

Thank you and I appreciate the work you're doing. 

Aamir

**Comment by cactuskid** [comment]
Hi. Currently the workaround for this would be to download the alphafold db structures ( or whatever structuress you need ) and run this as a job with a custom set of pdbs. Keep in mind that some crystal structures may have discontinuities or may be truncated proteins due to the constraints of crystalography and this may affect comparison with full length AFDB models for example.
