### ISSUE TITLE
question of Benchmarking experiments 

### ISSUE THREAD

**Issue by lzbsjtu** [DessimozLab/fold_tree#8]
you have done an excellent job.
I have some problem when running Benchmarking experiments.
snakemake  --profile slurmsimple/simple --use-conda -s ./workflow/Benchmarking_workflow --directory  ./path/to/your/data/OMA_data/LUCA
there is no file in the 'slurmsimple/' and no 'Benchmarking_workflow' in the './workflow'.
hope you could help me.

**Comment by cactuskid** [comment]
Thanks!

Sorry, there appears to be a filename error in this command. the benchmarking workflow in the workflow directory is just named benchmarking and not benchmarking_workflow.

I'll take a look at the readme. Also, slurmsimple is a module thats needed for this workflow on slurm clusters. Are you working in a slurm environment? If so you may need to use this submodule. Normally this is installed as a dependency for the git.


the repo is found here https://github.com/jdblischak/smk-simple-slurm/tree/962731f46784ca9867b124904703658785747066. 

simple is a folder in this repo where config files are found. You may need to modify these files in order to suit your slurm cluster. If you don't have a slurm cluster, snakemake provides documentation on how to deploy pipelines in other environments. Normally this should work since foldtree uses conda environments that should work across platforms.

https://snakemake.readthedocs.io/en/stable/executing/cluster.html


What kind of setup do you have? Maybe I can help with a bit more information. Also, which aspect of the benchmarking experiments are you interested in? I may just be able to send you some of the data since this process requires heavy computation ( thousands of protein families in structure and sequence formats using different treebuilding methods ).
